{
  "kind": "discovery#restDescription",
  "discoveryVersion": "v1",
  "id": "cloudidentity:v1alpha1",
  "name": "cloudidentity",
  "canonicalName": "Cloud Identity",
  "version": "v1alpha1",
  "revision": "0",
  "title": "Cloud Identity API",
  "description": "API for provisioning and managing identity resources.",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "documentationLink": "https://cloud.google.com/identity/",
  "protocol": "rest",
  "rootUrl": "https://cloudidentity.googleapis.com/",
  "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/",
  "servicePath": "",
  "baseUrl": "https://cloudidentity.googleapis.com/",
  "batchPath": "batch",
  "version_module": true,
  "fullyEncodeReservedExpansion": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-identity": {
          "description": "Private Service: https:\/\/www.googleapis.com\/auth\/cloud-identity"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        }
      }
    }
  },
  "resources": {
    "groups": {
      "methods": {
        "create": {
          "id": "cloudidentity.groups.create",
          "path": "v1alpha1/groups",
          "flatPath": "v1alpha1/groups",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity",
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Creates a `Group`."
        },
        "get": {
          "id": "cloudidentity.groups.get",
          "path": "v1alpha1/{+name}",
          "flatPath": "v1alpha1/groups/{groupsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity",
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Retrieves a `Group`."
        },
        "patch": {
          "id": "cloudidentity.groups.patch",
          "path": "v1alpha1/{+name}",
          "flatPath": "v1alpha1/groups/{groupsId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity",
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Updates a `Group`."
        },
        "delete": {
          "id": "cloudidentity.groups.delete",
          "path": "v1alpha1/{+name}",
          "flatPath": "v1alpha1/groups/{groupsId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity",
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Deletes a `Group`."
        },
        "lookup": {
          "id": "cloudidentity.groups.lookup",
          "path": "v1alpha1/groups:lookup",
          "flatPath": "v1alpha1/groups:lookup",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity",
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Looks up the [resource name](https:\/\/cloud.google.com\/apis\/design\/resource_names) of a `Group` by its `EntityKey`."
        },
        "search": {
          "id": "cloudidentity.groups.search",
          "path": "v1alpha1/groups:search",
          "flatPath": "v1alpha1/groups:search",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity",
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Searches for `Group` resources matching a specified query."
        },
        "list": {
          "id": "cloudidentity.groups.list",
          "path": "v1alpha1/groups",
          "flatPath": "v1alpha1/groups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity",
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Lists the `Group` resources under a customer or namespace."
        }
      }
      ,
      "resources": {
        "memberships": {
          "methods": {
            "create": {
              "id": "cloudidentity.groups.memberships.create",
              "path": "v1alpha1/{+parent}/memberships",
              "flatPath": "v1alpha1/groups/{groupsId}/memberships",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Creates a `Membership`."
            },
            "get": {
              "id": "cloudidentity.groups.memberships.get",
              "path": "v1alpha1/{+name}",
              "flatPath": "v1alpha1/groups/{groupsId}/memberships/{membershipsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Retrieves a `Membership`."
            },
            "patch": {
              "id": "cloudidentity.groups.memberships.patch",
              "path": "v1alpha1/{+name}",
              "flatPath": "v1alpha1/groups/{groupsId}/memberships/{membershipsId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Updates a `Membership`."
            },
            "delete": {
              "id": "cloudidentity.groups.memberships.delete",
              "path": "v1alpha1/{+name}",
              "flatPath": "v1alpha1/groups/{groupsId}/memberships/{membershipsId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Deletes a `Membership`."
            },
            "lookup": {
              "id": "cloudidentity.groups.memberships.lookup",
              "path": "v1alpha1/{+parent}/memberships:lookup",
              "flatPath": "v1alpha1/groups/{groupsId}/memberships:lookup",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Looks up the [resource name](https:\/\/cloud.google.com\/apis\/design\/resource_names) of a `Membership` by its `EntityKey`."
            },
            "list": {
              "id": "cloudidentity.groups.memberships.list",
              "path": "v1alpha1/{+parent}/memberships",
              "flatPath": "v1alpha1/groups/{groupsId}/memberships",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Lists the `Membership`s within a `Group`."
            },
            "modifyMembershipRoles": {
              "id": "cloudidentity.groups.memberships.modifyMembershipRoles",
              "path": "v1alpha1/{+name}:modifyMembershipRoles",
              "flatPath": "v1alpha1/groups/{groupsId}/memberships/{membershipsId}:modifyMembershipRoles",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Modifies the `MembershipRole`s of a `Membership`."
            },
            "searchTransitiveMemberships": {
              "id": "cloudidentity.groups.memberships.searchTransitiveMemberships",
              "path": "v1alpha1/{+parent}/memberships:searchTransitiveMemberships",
              "flatPath": "v1alpha1/groups/{groupsId}/memberships:searchTransitiveMemberships",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Search transitive memberships of a group."
            },
            "searchTransitiveGroups": {
              "id": "cloudidentity.groups.memberships.searchTransitiveGroups",
              "path": "v1alpha1/{+parent}/memberships:searchTransitiveGroups",
              "flatPath": "v1alpha1/groups/{groupsId}/memberships:searchTransitiveGroups",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Search transitive groups of a member."
            },
            "checkTransitiveMembership": {
              "id": "cloudidentity.groups.memberships.checkTransitiveMembership",
              "path": "v1alpha1/{+parent}/memberships:checkTransitiveMembership",
              "flatPath": "v1alpha1/groups/{groupsId}/memberships:checkTransitiveMembership",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Check a potential member for membership in a group."
            },
            "getMembershipGraph": {
              "id": "cloudidentity.groups.memberships.getMembershipGraph",
              "path": "v1alpha1/{+parent}/memberships:getMembershipGraph",
              "flatPath": "v1alpha1/groups/{groupsId}/memberships:getMembershipGraph",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity",
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Get a membership graph of a member or member\/group."
            }
          }
        }
      }
    }
  },
  "basePath": ""
}