{
  "kind": "discovery#restDescription",
  "discoveryVersion": "v1",
  "id": "bigtableadmin:v2",
  "name": "bigtableadmin",
  "canonicalName": "Bigtable Admin",
  "version": "v2",
  "revision": "0",
  "title": "Cloud Bigtable Admin API",
  "description": "Administer your Cloud Bigtable tables and instances.",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "documentationLink": "https://cloud.google.com/bigtable/",
  "protocol": "rest",
  "rootUrl": "https://bigtableadmin.googleapis.com/",
  "mtlsRootUrl": "https://bigtableadmin.mtls.googleapis.com/",
  "servicePath": "",
  "baseUrl": "https://bigtableadmin.googleapis.com/",
  "batchPath": "batch",
  "version_module": true,
  "fullyEncodeReservedExpansion": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/bigtable.admin": {
          "description": "Administer your Cloud Bigtable tables and clusters"
        },
        "https://www.googleapis.com/auth/bigtable.admin.cluster": {
          "description": "Administer your Cloud Bigtable clusters"
        },
        "https://www.googleapis.com/auth/bigtable.admin.instance": {
          "description": "Administer your Cloud Bigtable clusters"
        },
        "https://www.googleapis.com/auth/bigtable.admin.table": {
          "description": "Administer your Cloud Bigtable tables"
        },
        "https://www.googleapis.com/auth/cloud-bigtable.admin": {
          "description": "Administer your Cloud Bigtable tables and clusters"
        },
        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster": {
          "description": "Administer your Cloud Bigtable clusters"
        },
        "https://www.googleapis.com/auth/cloud-bigtable.admin.table": {
          "description": "Administer your Cloud Bigtable tables"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/cloud-platform.read-only": {
          "description": "View your data across Google Cloud services and see the email address of your Google Account"
        }
      }
    }
  },
  "resources": {
    "operations": {
      "methods": {
        "get": {
          "id": "bigtableadmin.operations.get",
          "path": "v2/{+name}",
          "flatPath": "v2/operations/{operationsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/bigtable.admin",
            "https://www.googleapis.com/auth/bigtable.admin.cluster",
            "https://www.googleapis.com/auth/bigtable.admin.instance",
            "https://www.googleapis.com/auth/cloud-bigtable.admin",
            "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/cloud-platform.read-only"
          ],
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
        },
        "delete": {
          "id": "bigtableadmin.operations.delete",
          "path": "v2/{+name}",
          "flatPath": "v2/operations/{operationsId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/bigtable.admin",
            "https://www.googleapis.com/auth/bigtable.admin.cluster",
            "https://www.googleapis.com/auth/bigtable.admin.instance",
            "https://www.googleapis.com/auth/cloud-bigtable.admin",
            "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`."
        },
        "cancel": {
          "id": "bigtableadmin.operations.cancel",
          "path": "v2/{+name}:cancel",
          "flatPath": "v2/operations/{operationsId}:cancel",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/bigtable.admin",
            "https://www.googleapis.com/auth/bigtable.admin.cluster",
            "https://www.googleapis.com/auth/bigtable.admin.instance",
            "https://www.googleapis.com/auth/cloud-bigtable.admin",
            "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]"
        }
      }
      ,
      "resources": {
        "projects": {
          "resources": {
            "operations": {
              "methods": {
                "list": {
                  "id": "bigtableadmin.operations.projects.operations.list",
                  "path": "v2/{+name}/operations",
                  "flatPath": "v2/operations/projects/{projectsId}/operations",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`. NOTE: the `name` binding allows API services to override the binding to use different resource name schemes, such as `users\/*\/operations`. To override the binding, API services can add a binding such as `\"\/v1\/{name=users\/*}\/operations\"` to their service configuration. For backwards compatibility, the default name include[...]"
                }
              }
            }
          }
        }
      }
    },
    "projects": {
      "resources": {
        "instances": {
          "methods": {
            "create": {
              "id": "bigtableadmin.projects.instances.create",
              "path": "v2/{+parent}/instances",
              "flatPath": "v2/projects/{projectsId}/instances",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Create an instance within a project. Note that exactly one of Cluster.serve_nodes and Cluster.cluster_config.cluster_autoscaling_config can be set. If serve_nodes is set to non-zero, then the cluster is manually scaled. If cluster_config.cluster_autoscaling_config is non-empty, then autoscaling is enabled."
            },
            "get": {
              "id": "bigtableadmin.projects.instances.get",
              "path": "v2/{+name}",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only"
              ],
              "description": "Gets information about an instance."
            },
            "list": {
              "id": "bigtableadmin.projects.instances.list",
              "path": "v2/{+parent}/instances",
              "flatPath": "v2/projects/{projectsId}/instances",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only"
              ],
              "description": "Lists information about instances in a project."
            },
            "update": {
              "id": "bigtableadmin.projects.instances.update",
              "path": "v2/{+name}",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Updates an instance within a project. This method updates only the display name and type for an Instance. To update other Instance properties, such as labels, use PartialUpdateInstance."
            },
            "partialUpdateInstance": {
              "id": "bigtableadmin.projects.instances.partialUpdateInstance",
              "path": "v2/{+name}",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Partially updates an instance within a project. This method can modify all fields of an Instance and is the preferred way to update an Instance."
            },
            "delete": {
              "id": "bigtableadmin.projects.instances.delete",
              "path": "v2/{+name}",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Delete an instance from a project."
            },
            "getIamPolicy": {
              "id": "bigtableadmin.projects.instances.getIamPolicy",
              "path": "v2/{+resource}:getIamPolicy",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}:getIamPolicy",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Gets the access control policy for an instance resource. Returns an empty policy if an instance exists but does not have a policy set."
            },
            "setIamPolicy": {
              "id": "bigtableadmin.projects.instances.setIamPolicy",
              "path": "v2/{+resource}:setIamPolicy",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}:setIamPolicy",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Sets the access control policy on an instance resource. Replaces any existing policy."
            },
            "testIamPermissions": {
              "id": "bigtableadmin.projects.instances.testIamPermissions",
              "path": "v2/{+resource}:testIamPermissions",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}:testIamPermissions",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Returns permissions that the caller has on the specified instance resource."
            }
          }
          ,
          "resources": {
            "clusters": {
              "methods": {
                "create": {
                  "id": "bigtableadmin.projects.instances.clusters.create",
                  "path": "v2/{+parent}/clusters",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Creates a cluster within an instance. Note that exactly one of Cluster.serve_nodes and Cluster.cluster_config.cluster_autoscaling_config can be set. If serve_nodes is set to non-zero, then the cluster is manually scaled. If cluster_config.cluster_autoscaling_config is non-empty, then autoscaling is enabled."
                },
                "get": {
                  "id": "bigtableadmin.projects.instances.clusters.get",
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Gets information about a cluster."
                },
                "list": {
                  "id": "bigtableadmin.projects.instances.clusters.list",
                  "path": "v2/{+parent}/clusters",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Lists information about clusters in an instance."
                },
                "update": {
                  "id": "bigtableadmin.projects.instances.clusters.update",
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}",
                  "httpMethod": "PUT",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Updates a cluster within an instance. Note that UpdateCluster does not support updating cluster_config.cluster_autoscaling_config. In order to update it, you must use PartialUpdateCluster."
                },
                "partialUpdateCluster": {
                  "id": "bigtableadmin.projects.instances.clusters.partialUpdateCluster",
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Partially updates a cluster within a project. This method is the preferred way to update a Cluster. To enable and update autoscaling, set cluster_config.cluster_autoscaling_config. When autoscaling is enabled, serve_nodes is treated as an OUTPUT_ONLY field, meaning that updates to it are ignored. Note that an update cannot simultaneously set serve_nodes to non-zero and cluster_config.cluster_autoscaling_config to non-empty, and also specify both in the update_ma[...]"
                },
                "delete": {
                  "id": "bigtableadmin.projects.instances.clusters.delete",
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Deletes a cluster from an instance."
                }
              }
              ,
              "resources": {
                "hotTablets": {
                  "methods": {
                    "list": {
                      "id": "bigtableadmin.projects.instances.clusters.hotTablets.list",
                      "path": "v2/{+parent}/hotTablets",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/hotTablets",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.cluster",
                        "https://www.googleapis.com/auth/bigtable.admin.instance",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "description": "Lists hot tablets in a cluster, within the time range provided. Hot tablets are ordered based on CPU usage."
                    }
                  }
                },
                "backups": {
                  "methods": {
                    "create": {
                      "id": "bigtableadmin.projects.instances.clusters.backups.create",
                      "path": "v2/{+parent}/backups",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "description": "Starts creating a new Cloud Bigtable Backup. The returned backup long-running operation can be used to track creation of the backup. The metadata field type is CreateBackupMetadata. The response field type is Backup, if successful. Cancelling the returned operation will stop the creation and delete the backup."
                    },
                    "get": {
                      "id": "bigtableadmin.projects.instances.clusters.backups.get",
                      "path": "v2/{+name}",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "description": "Gets metadata on a pending or completed Cloud Bigtable Backup."
                    },
                    "patch": {
                      "id": "bigtableadmin.projects.instances.clusters.backups.patch",
                      "path": "v2/{+name}",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}",
                      "httpMethod": "PATCH",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "description": "Updates a pending or completed Cloud Bigtable Backup."
                    },
                    "delete": {
                      "id": "bigtableadmin.projects.instances.clusters.backups.delete",
                      "path": "v2/{+name}",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "description": "Deletes a pending or completed Cloud Bigtable backup."
                    },
                    "list": {
                      "id": "bigtableadmin.projects.instances.clusters.backups.list",
                      "path": "v2/{+parent}/backups",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "description": "Lists Cloud Bigtable backups. Returns both completed and pending backups."
                    },
                    "copy": {
                      "id": "bigtableadmin.projects.instances.clusters.backups.copy",
                      "path": "v2/{+parent}/backups:copy",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups:copy",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "description": "Copy a Cloud Bigtable backup to a new backup in the destination cluster located in the destination instance and project."
                    },
                    "getIamPolicy": {
                      "id": "bigtableadmin.projects.instances.clusters.backups.getIamPolicy",
                      "path": "v2/{+resource}:getIamPolicy",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}:getIamPolicy",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "description": "Gets the access control policy for a Table resource. Returns an empty policy if the resource exists but does not have a policy set."
                    },
                    "setIamPolicy": {
                      "id": "bigtableadmin.projects.instances.clusters.backups.setIamPolicy",
                      "path": "v2/{+resource}:setIamPolicy",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}:setIamPolicy",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "description": "Sets the access control policy on a Table resource. Replaces any existing policy."
                    },
                    "testIamPermissions": {
                      "id": "bigtableadmin.projects.instances.clusters.backups.testIamPermissions",
                      "path": "v2/{+resource}:testIamPermissions",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}:testIamPermissions",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "description": "Returns permissions that the caller has on the specified table resource."
                    }
                  }
                }
              }
            },
            "appProfiles": {
              "methods": {
                "create": {
                  "id": "bigtableadmin.projects.instances.appProfiles.create",
                  "path": "v2/{+parent}/appProfiles",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Creates an app profile within an instance."
                },
                "get": {
                  "id": "bigtableadmin.projects.instances.appProfiles.get",
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles/{appProfilesId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Gets information about an app profile."
                },
                "list": {
                  "id": "bigtableadmin.projects.instances.appProfiles.list",
                  "path": "v2/{+parent}/appProfiles",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Lists information about app profiles in an instance."
                },
                "patch": {
                  "id": "bigtableadmin.projects.instances.appProfiles.patch",
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles/{appProfilesId}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Updates an app profile within an instance."
                },
                "delete": {
                  "id": "bigtableadmin.projects.instances.appProfiles.delete",
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles/{appProfilesId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Deletes an app profile from an instance."
                }
              }
            },
            "tables": {
              "methods": {
                "create": {
                  "id": "bigtableadmin.projects.instances.tables.create",
                  "path": "v2/{+parent}/tables",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Creates a new table in the specified instance. The table can be created with a full set of initial column families, specified in the request."
                },
                "list": {
                  "id": "bigtableadmin.projects.instances.tables.list",
                  "path": "v2/{+parent}/tables",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Lists all tables served from a specified instance."
                },
                "get": {
                  "id": "bigtableadmin.projects.instances.tables.get",
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Gets metadata information about the specified table."
                },
                "patch": {
                  "id": "bigtableadmin.projects.instances.tables.patch",
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Updates a specified table."
                },
                "delete": {
                  "id": "bigtableadmin.projects.instances.tables.delete",
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Permanently deletes a specified table and all of its data."
                },
                "undelete": {
                  "id": "bigtableadmin.projects.instances.tables.undelete",
                  "path": "v2/{+name}:undelete",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:undelete",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Restores a specified table which was accidentally deleted."
                },
                "modifyColumnFamilies": {
                  "id": "bigtableadmin.projects.instances.tables.modifyColumnFamilies",
                  "path": "v2/{+name}:modifyColumnFamilies",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:modifyColumnFamilies",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Performs a series of column family modifications on the specified table. Either all or none of the modifications will occur before this method returns, but data requests received prior to that point may see a table where only some modifications have taken effect."
                },
                "dropRowRange": {
                  "id": "bigtableadmin.projects.instances.tables.dropRowRange",
                  "path": "v2/{+name}:dropRowRange",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:dropRowRange",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Permanently drop\/delete a row range from a specified table. The request can specify whether to delete all rows in a table, or only those that match a particular prefix."
                },
                "generateConsistencyToken": {
                  "id": "bigtableadmin.projects.instances.tables.generateConsistencyToken",
                  "path": "v2/{+name}:generateConsistencyToken",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:generateConsistencyToken",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Generates a consistency token for a Table, which can be used in CheckConsistency to check whether mutations to the table that finished before this call started have been replicated. The tokens will be available for 90 days."
                },
                "checkConsistency": {
                  "id": "bigtableadmin.projects.instances.tables.checkConsistency",
                  "path": "v2/{+name}:checkConsistency",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:checkConsistency",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Checks replication consistency based on a consistency token, that is, if replication has caught up based on the conditions specified in the token and the check request."
                },
                "restore": {
                  "id": "bigtableadmin.projects.instances.tables.restore",
                  "path": "v2/{+parent}/tables:restore",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables:restore",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Create a new table by restoring from a completed backup. The returned table long-running operation can be used to track the progress of the operation, and to cancel it. The metadata field type is RestoreTableMetadata. The response type is Table, if successful."
                },
                "getIamPolicy": {
                  "id": "bigtableadmin.projects.instances.tables.getIamPolicy",
                  "path": "v2/{+resource}:getIamPolicy",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:getIamPolicy",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Gets the access control policy for a Table resource. Returns an empty policy if the resource exists but does not have a policy set."
                },
                "setIamPolicy": {
                  "id": "bigtableadmin.projects.instances.tables.setIamPolicy",
                  "path": "v2/{+resource}:setIamPolicy",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:setIamPolicy",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Sets the access control policy on a Table resource. Replaces any existing policy."
                },
                "testIamPermissions": {
                  "id": "bigtableadmin.projects.instances.tables.testIamPermissions",
                  "path": "v2/{+resource}:testIamPermissions",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:testIamPermissions",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Returns permissions that the caller has on the specified table resource."
                }
              }
            }
          }
        },
        "locations": {
          "methods": {
            "list": {
              "id": "bigtableadmin.projects.locations.list",
              "path": "v2/{+name}/locations",
              "flatPath": "v2/projects/{projectsId}/locations",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only"
              ],
              "description": "Lists information about the supported locations for this service."
            },
            "get": {
              "id": "bigtableadmin.projects.locations.get",
              "path": "v2/{+name}",
              "flatPath": "v2/projects/{projectsId}/locations/{locationsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only"
              ],
              "description": "Gets information about a location."
            }
          }
        }
      }
    }
  },
  "basePath": ""
}